### PR TITLE
Refactor Alerts

### PR DESCRIPTION
**Pull request by crissdev**
- Use controllerAs syntax for Alerts page
- Fix freeze/unfreeze option
- Add 2 more tests to cover changing of freeze/unfreeze option

### CODE REVIEW

**Comment by crissdev** [comment]
That was quick! :+1:

**Comment by crissdev** [comment]
I noticed some e2e tests but I wasn't sure about the naming convention you want to use. The protractor configuration contains just one test case. Any hints you want to share on that? Thanks.

**Comment by TusharaFernando** [comment]
I'm  also not sure.  I think that the dashboard should offer some guidance on e2e testing.  Do you think that there should be a file for each view?

**Comment by crissdev** [comment]
My first thought on this was to keep e2e tests in a separate directory, since they describe use cases.
Yes, a file for each view would be a way to go I woud say - considering Protractor docs for [page objects](http://angular.github.io/protractor/#/page-objects)).

Here's what I have so far for the alerts page.  I didn't include it so far because I wanted your oppinion on e2e tests first.

``` js
describe('Alerts Page', function() {

  function AlertsPage() {
    this.filterInut = element(by.binding('alertsCtrl.displayControl.filter'));
    this.switchControl = element(by.binding('alertsCtrl.displayControl.displayFrozen'));
    this.alertItems = element.all(
      by.repeater('alert in alertsCtrl.alerts'));

    this.get = function() {
      browser.get('http://localhost:3010/alerts');
      browser.waitForAngular();
    };
  }

  it('should be initialized with expected defaults', function() {
    var alertsPage = new AlertsPage();
    alertsPage.get();

    expect(alertsPage.switchControl.getText()).toEqual('Freeze Display');
    expect(alertsPage.filterInut.getText()).toEqual('Freeze Display');
  });

});
```

**Comment by TusharaFernando** [comment]
I think that's a really good idea.  Include it and I'll try and add the tests for the other pages tomorrow.

**Comment by crissdev** [comment]
Great. I'm going to do this tomorrow 'cause now it's quite late here :-)

**Comment by crissdev** [comment]
@TusharaFernando See PR #6.

**Pull request merged**
